name: Order Service

on:
  push:
    paths:
      - "order-service/**"

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Running Test
        run: cd order-service && go test -v ./...
